### ISSUE TITLE
camera doesn't work.

### ISSUE THREAD

**Issue by shellbombs** [pelya/android-keyboard-gadget#79]
First i really appreciate your EFFORTS.

Here are part of the outputs of "adb logcat"

03-06 14:46:52.917 31713 31744 I HID keyboard: Starting VNC server
03-06 14:46:52.918 31713 31744 I HID keyboard: Opening camera: class 0x100005 methods 0xb6b8bb90 0xb6b8bb6c
03-06 14:46:52.918 31713 31744 D SDL-CAMERA: initCamera: 1280x720 FPS 5
03-06 14:46:52.918 31713 31744 D SDL-CAMERA: setupCamera: 1280x720 FPS 5000
03-06 14:46:52.926 31033 31594 I chatty  : uid=1013(media) Binder:31033_2 expire 6 lines
03-06 14:46:52.927 31713 31744 W CameraBase: An error occurred while connecting to camera 0: Service not available
03-06 14:46:52.927 31713 31744 W SDL-CAMERA: initCamera exception: java.lang.RuntimeException: Fail to connect to camera service
03-06 14:46:52.927 31713 31744 W SDL-CAMERA: 	at android.hardware.Camera.<init>(Camera.java:575)
03-06 14:46:52.927 31713 31744 W SDL-CAMERA: 	at android.hardware.Camera.open(Camera.java:404)
03-06 14:46:52.927 31713 31744 W SDL-CAMERA: 	at remote.hid.keyboard.client.CameraFeed.setupCamera(Unknown Source)
03-06 14:46:52.927 31713 31744 W SDL-CAMERA: 	at remote.hid.keyboard.client.CameraFeed.initCamera(Unknown Source)
03-06 14:46:52.927 31713 31744 W SDL-CAMERA: 	at remote.hid.keyboard.client.DemoRenderer.nativeInit(Native Method)
03-06 14:46:52.927 31713 31744 W SDL-CAMERA: 	at remote.hid.keyboard.client.DemoRenderer.onDrawFrame(Unknown Source)
03-06 14:46:52.927 31713 31744 W SDL-CAMERA: 	at remote.hid.keyboard.client.GLSurfaceView_SDL$GLThread.run(Unknown Source)
03-06 14:46:52.927 31713 31744 D SDL-CAMERA: initCamera done
03-06 14:46:52.927 31713 31744 I HID keyboard: Camera opened
03-06 14:46:52.957 31713 31744 I HID keyboard: VNC server started

I'm using lineage os (android 7.1.1), i build the kernel with HID supported.

**Comment by shellbombs** [comment]
sorry, my bad, i didn't give it the camera permission.
